In [1]:
import pandas as pd, requests, json
from sqlalchemy import create_engine

### Extract CSVs into DataFrames

In [2]:
hotel = "Resources/Datafiniti_Hotel_Reviews.csv"
hotel_df = pd.read_csv(hotel)
#hotel_df.head()

In [3]:
hotel2 = "Resources/Datafiniti_Hotel_Reviews_Jun19.csv"
hotel2_df = pd.read_csv(hotel2)
#hotel2_df.head()

In [4]:
hotel3 = "Resources/7282_1.csv"
hotel3_df = pd.read_csv(hotel3)
#hotel3_df.head()

### Transform 7282_1  DataFrame

In [5]:
# Create a filtered dataframe from specific columns for Hotel info
hot3 = ["name","address","city","postalCode","province","latitude","longitude","categories","reviews.rating","reviews.text"]
hotel3_transformed = hotel3_df[hot3].copy()

# Rename the Column Headers
hotel3_transformed = hotel3_transformed.rename(columns={"name":"Name","address":"Address","city":"City",
                                                        "postalCode":"Postal Code","province":"Province",
                                                        "latitude":"Latitude","longitude":"Longitude",
                                                        "categories":"Category","reviews.rating":"Review Rating",
                                                        "reviews.text":"Review Comments"})


hotel3_transformed.set_index("Name",inplace=True)

#hotel3_transformed.head()

### Transform Datafiniti_Hotel_Reviews DataFrame

In [6]:
# Create a filtered dataframe from specific columns for Pokemon
hot = ["name","address","city","province","postalCode","country","longitude","latitude","categories","reviews.rating","reviews.text","websites"]
hotel_transformed = hotel_df[hot].copy()

# Rename the Column Headers
hotel_transformed = hotel_transformed.rename(columns={"name":"Name","address":"Address","city":"City","province":"State",
                                                        "postalCode":"Postal Code","country":"Country","latitude":"Latitude",
                                                        "longitude":"Longitude","categories":"Category","reviews.rating":"Review Rating",
                                                        "reviews.text":"Review Comments"})


hotel_transformed.set_index("Name",inplace=True)

#hotel_transformed.head()

### Transform Datafiniti_Hotel_Reviews_Jun19. DataFrame

In [7]:
# Create a filtered dataframe from specific columns for Pokemon
hot2 = ["name","address","city","province","postalCode","country","longitude","latitude","categories","reviews.rating","reviews.text","websites"]
hotel2_transformed = hotel2_df[hot].copy()

# Rename the Column Headers
hotel2_transformed = hotel2_transformed.rename(columns={"name":"Name","address":"Address","city":"City","province":"State",
                                                        "postalCode":"Postal Code","country":"Country","latitude":"Latitude",
                                                        "longitude":"Longitude","categories":"Category","reviews.rating":"Review Rating",
                                                        "reviews.text":"Review Comments"})


hotel2_transformed.set_index("Name",inplace=True)

#hotel2_transformed.head()

### Create database connection

In [8]:
connection_string = "postgres:postgres@localhost:5432/hotels_db"
engine = create_engine(f'postgresql://{connection_string}')

In [9]:
# Confirm tables
engine.table_names()

<ipython-input-9-2d97e9123e98>:2: SADeprecationWarning: The Engine.table_names() method is deprecated and will be removed in a future release.  Please refer to Inspector.get_table_names(). (deprecated since: 1.4)
  engine.table_names()

['Hotel', 'Hotel2', 'Hotel3', 'hotel', 'hotel2', 'hotel3']

### Create database connection

In [10]:
hotel_transformed.to_sql(name='hotel', con=engine, if_exists='append', index=True)

In [11]:
hotel =pd.read_sql_query('select * from "hotel"', con=engine)

In [12]:
pd.read_sql_query('select * from "hotel"', con=engine).head()

,Name,Address,City,State,Postal Code,Country,Longitude,Latitude,Category,Review Rating,Review Comments,websites
0,Rancho Valencia Resort Spa,5921 Valencia Cir,Rancho Santa Fe,CA,92067,US,-117.186136,32.990959,"Hotels,Hotels and motels,Hotel and motel reser...",5.0,Our experience at Rancho Valencia was absolute...,http://www.ranchovalencia.com
1,Rancho Valencia Resort Spa,5921 Valencia Cir,Rancho Santa Fe,CA,92067,US,-117.186136,32.990959,"Hotels,Hotels and motels,Hotel and motel reser...",5.0,Amazing place. Everyone was extremely warm and...,http://www.ranchovalencia.com
2,Rancho Valencia Resort Spa,5921 Valencia Cir,Rancho Santa Fe,CA,92067,US,-117.186136,32.990959,"Hotels,Hotels and motels,Hotel and motel reser...",5.0,We booked a 3 night stay at Rancho Valencia to...,http://www.ranchovalencia.com
3,Aloft Arundel Mills,7520 Teague Rd,Hanover,MD,21076,US,-76.716341,39.155929,"Hotels,Hotels and motels,Travel agencies and b...",2.0,Currently in bed writing this for the past hr ...,http://www.starwoodhotels.com/alofthotels/prop...
4,Aloft Arundel Mills,7520 Teague Rd,Hanover,MD,21076,US,-76.716341,39.155929,"Hotels,Hotels and motels,Travel agencies and b...",5.0,I live in Md and the Aloft is my Home away fro...,http://www.starwoodhotels.com/alofthotels/prop...

In [13]:
hotel2_transformed.to_sql(name='hotel2', con=engine, if_exists='append', index=True)

In [14]:
hotel2 =pd.read_sql_query('select * from "hotel2"', con=engine)

In [15]:
pd.read_sql_query('select * from "hotel2"', con=engine).head()

,Name,Address,City,State,Postal Code,Country,Longitude,Latitude,Category,Review Rating,Review Comments,websites
0,Best Western Plus South Coast Inn,5620 Calle Real,Goleta,CA,93117,US,-119.81979,34.44178,"Hotels,Hotels and motels,Hotel and motel mgmt....",3,"This hotel was nice and quiet. Did not know, t...",https://www.bestwestern.com/en_US/book/hotel-r...
1,Best Western Carmel's Town House Lodge,5th And San Carlos PO Box 3574,Carmel by the Sea,CA,93921,US,-121.92194,36.55722,"Hotels,Lodging,Hotel",4,We stayed in the king suite with the separatio...,http://www.bestwestern.com
2,Best Western Carmel's Town House Lodge,5th And San Carlos PO Box 3574,Carmel by the Sea,CA,93921,US,-121.92194,36.55722,"Hotels,Lodging,Hotel",3,"Parking was horrible, somebody ran into my ren...",http://www.bestwestern.com
3,Best Western Carmel's Town House Lodge,5th And San Carlos PO Box 3574,Carmel by the Sea,CA,93921,US,-121.92194,36.55722,"Hotels,Lodging,Hotel",5,Not cheap but excellent location. Price is som...,http://www.bestwestern.com
4,Best Western Carmel's Town House Lodge,5th And San Carlos PO Box 3574,Carmel by the Sea,CA,93921,US,-121.92194,36.55722,"Hotels,Lodging,Hotel",2,If you get the room that they advertised on th...,http://www.bestwestern.com

In [16]:
hotel3_transformed.to_sql(name='hotel3', con=engine, if_exists='append', index=True)

In [17]:
hotel3 =pd.read_sql_query('select * from "hotel3"', con=engine)

In [18]:
pd.read_sql_query('select * from "hotel3"', con=engine).head()

,Name,Address,City,Postal Code,Province,Latitude,Longitude,Category,Review Rating,Review Comments
0,Hotel Russo Palace,Riviera San Nicol 11/a,Mableton,30126,GA,45.421611,12.376187,Hotels,4.0,Pleasant 10 min walk along the sea front to th...
1,Hotel Russo Palace,Riviera San Nicol 11/a,Mableton,30126,GA,45.421611,12.376187,Hotels,5.0,Really lovely hotel. Stayed on the very top fl...
2,Hotel Russo Palace,Riviera San Nicol 11/a,Mableton,30126,GA,45.421611,12.376187,Hotels,5.0,Ett mycket bra hotell. Det som drog ner betyge...
3,Hotel Russo Palace,Riviera San Nicol 11/a,Mableton,30126,GA,45.421611,12.376187,Hotels,5.0,We stayed here for four nights in October. The...
4,Hotel Russo Palace,Riviera San Nicol 11/a,Mableton,30126,GA,45.421611,12.376187,Hotels,5.0,We stayed here for four nights in October. The...

In [19]:
# Create a filtered dataframe from specific columns for hotel
hot2 = ["name","address","city","province","postalCode","country","longitude","latitude"]
hotel2_transformed = hotel2_df[hot].copy()

# Rename the Column Headers
hotel2_transformed = hotel2_transformed.rename(columns={"name":"Name","address":"Address","city":"City","province":"State",
                                                        "postalCode":"Postal Code","country":"Country","latitude":"Latitude",
                                                        "longitude":"Longitude"})


hotel2_transformed.set_index("Name",inplace=True)

hotel2_transformed.head()

,Address,City,State,Postal Code,Country,Longitude,Latitude,categories,reviews.rating,reviews.text,websites
Name,,,,,,,,,,,
Best Western Plus South Coast Inn,5620 Calle Real,Goleta,CA,93117,US,-119.81979,34.44178,"Hotels,Hotels and motels,Hotel and motel mgmt....",3,"This hotel was nice and quiet. Did not know, t...",https://www.bestwestern.com/en_US/book/hotel-r...
Best Western Carmel's Town House Lodge,5th And San Carlos PO Box 3574,Carmel by the Sea,CA,93921,US,-121.92194,36.55722,"Hotels,Lodging,Hotel",4,We stayed in the king suite with the separatio...,http://www.bestwestern.com
Best Western Carmel's Town House Lodge,5th And San Carlos PO Box 3574,Carmel by the Sea,CA,93921,US,-121.92194,36.55722,"Hotels,Lodging,Hotel",3,"Parking was horrible, somebody ran into my ren...",http://www.bestwestern.com
Best Western Carmel's Town House Lodge,5th And San Carlos PO Box 3574,Carmel by the Sea,CA,93921,US,-121.92194,36.55722,"Hotels,Lodging,Hotel",5,Not cheap but excellent location. Price is som...,http://www.bestwestern.com
Best Western Carmel's Town House Lodge,5th And San Carlos PO Box 3574,Carmel by the Sea,CA,93921,US,-121.92194,36.55722,"Hotels,Lodging,Hotel",2,If you get the room that they advertised on th...,http://www.bestwestern.com

## Merge Hotels for Map

In [20]:
hotel_combo = pd.concat([hotel, hotel2]).drop_duplicates()
hotel_map=hotel_combo[['Name','Address','City','State','Postal Code','Longitude','Latitude']].dropna()
hotel_map['Latitude'] = hotel_map['Latitude'].astype(float)
hotel_map['Longitude'] = hotel_map['Longitude'].astype(float)
hotel_map

,Name,Address,City,State,Postal Code,Longitude,Latitude
0,Rancho Valencia Resort Spa,5921 Valencia Cir,Rancho Santa Fe,CA,92067,-117.186136,32.990959
1,Rancho Valencia Resort Spa,5921 Valencia Cir,Rancho Santa Fe,CA,92067,-117.186136,32.990959
2,Rancho Valencia Resort Spa,5921 Valencia Cir,Rancho Santa Fe,CA,92067,-117.186136,32.990959
3,Aloft Arundel Mills,7520 Teague Rd,Hanover,MD,21076,-76.716341,39.155929
4,Aloft Arundel Mills,7520 Teague Rd,Hanover,MD,21076,-76.716341,39.155929
...,...,...,...,...,...,...,...
10065,Hampton Inn Hampton-newport News,3101 Coliseum Dr,Hampton,VA,23666,-76.393310,37.057650
10066,Hampton Inn Hampton-newport News,3101 Coliseum Dr,Hampton,VA,23666,-76.393310,37.057650
10067,Hampton Inn Hampton-newport News,3101 Coliseum Dr,Hampton,VA,23666,-76.393310,37.057650
10068,Roseberry's Inn,7886 Main Street,Hunter,NY,12442,-74.215309,42.210915
10069,Hampton Inn-lindale/tyler,3505 S Main St,Lindale,TX,75771,-95.390420,32.469540

In [21]:
type(hotel_map)

pandas.core.frame.DataFrame

In [22]:
small_hotel_map= hotel_map
states = ['NY','MA','NJ']
small_hotel_map.loc[hotel_map['State'].isin(states)]
small_hotel_map=small_hotel_map.loc[hotel_map['State'].isin(states)]
small_hotel_map.head()

,Name,Address,City,State,Postal Code,Longitude,Latitude
27,EconoLodge,998 W Landis Ave,Vineland,NJ,8360,-75.044475,39.487449
28,EconoLodge,998 W Landis Ave,Vineland,NJ,8360,-75.044475,39.487449
32,The Boxer,107 Merrimac Street,Boston,MA,2114,-71.062400,42.363911
105,The Boxer,107 Merrimac Street,Boston,MA,2114,-71.062400,42.363911
106,The Boxer,107 Merrimac Street,Boston,MA,2114,-71.062400,42.363911

In [23]:
type(small_hotel_map)

pandas.core.frame.DataFrame

In [24]:
def df_to_geojson(df, properties, lat='Latitude', lon='Longitude'):
    # create a new python dict to contain our geojson data, using geojson format
    geojson = {'type':'FeatureCollection', 'features':[]}

    # loop through each row in the dataframe and convert each row to geojson format
    
    for _, row in df.iterrows():
        # create a feature template to fill in
        feature = {'type':'Feature',
                   'properties':{},
                   'geometry':{'type':'Point',
                               'coordinates':[]}}

        # fill in the coordinates
       # try:
        feature['geometry']['coordinates'] = [row[lon],row[lat]]
        #except KeyError:
         #   print(row)
            
        # for each column, get the value and add it as a new feature property
        for prop in properties:
            feature['properties'][prop] = row[prop]
        
        # add this feature (aka, converted dataframe row) to the list of features inside our dict
        geojson['features'].append(feature)
    
    return geojson

In [25]:
cols = ['Name','Address','City','State','Postal Code']
geojson = df_to_geojson(hotel_map, cols)

In [26]:
cols = ['Name','Address','City','State','Postal Code']
geojson2 = df_to_geojson(small_hotel_map, cols)

In [27]:
# save the geojson result to a file
output_filename = 'hotel.js'
with open(output_filename, 'w') as output_file:
    output_file.write('var dataset = {};'.format(json.dumps(geojson2)))
    
# how many features did we save to the geojson file?
print('{} geotagged features saved to file'.format(len(geojson['features'])))

19766 geotagged features saved to file

In [28]:
# save the geojson result to a file
output_filename = 'smaller hotel.js'
with open(output_filename, 'w') as output_file:
    output_file.write('var dataset = {};'.format(json.dumps(geojson)))
    
# how many features did we save to the geojson file?
print('{} geotagged features saved to file'.format(len(geojson2['features'])))

901 geotagged features saved to file